name: Build and Deploy to Netlify CI/CD
on:
  push:
    branches:
      - development
      - master
      - canary
      - setup-better-ci-cd
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment:
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Read old BUILD_VERSION from config.json
        run: |
          OLD_VERSION=$(jq -r '.BUILD_VERSION' app/config/config.json)
          echo "Old BUILD_VERSION: $OLD_VERSION"
  
      - name: Update BUILD_VERSION only when in development branch
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/setup-better-ci-cd'
        run: |
          CONFIG_PATH="app/config/config.json"
          # Read the config.json file
          CONFIG=$(<"$CONFIG_PATH")
          # Extract old BUILD_VERSION
          OLD_VERSION=$(jq -r '.BUILD_VERSION' <<< "$CONFIG")
          echo "Old BUILD_VERSION: $OLD_VERSION"
          # Increment the BUILD_VERSION using semantic versioning
          NEW_VERSION=$(echo "$OLD_VERSION" | awk -F '.' '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "New BUILD_VERSION: $NEW_VERSION"
          # Update the config.json file with the new BUILD_VERSION
          UPDATED_CONFIG=$(echo "$CONFIG" | jq --arg new_version "$NEW_VERSION" '.BUILD_VERSION = $new_version')
          echo "$UPDATED_CONFIG" > "$CONFIG_PATH"
          git config --global user.email "me-gh-action-bot@massenergize.org"
          git config --global user.name "Version Update Bot"
          git add "$CONFIG_PATH"
          git commit -m "Bump BUILD_VERSION to $NEW_VERSION"
          git push origin HEAD:$GITHUB_REF

      - name: Create and push tag
        run: |
          BUILD_VERSION=$(jq -r '.BUILD_VERSION' < app/config/config.json)
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          TAG_NAME="$BRANCH_NAME@$BUILD_VERSION"
          echo "BUILD_VERSION: $BUILD_VERSION"
          echo "Branch name: $BRANCH_NAME"
          echo "New tag name: $TAG_NAME"
          git tag -a "$TAG_NAME" -m "Version $BUILD_VERSION"
          git push origin "$TAG_NAME"

      - name: Set Prod/Canary Environment Variables 🚀
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/canary' 
        run: |
            echo "Setting prod branch secrets..."
            echo "REACT_APP_SENTRY_DSN=${{ secrets.PROD_REACT_APP_SENTRY_DSN }}" >> $GITHUB_ENV
            echo "REACT_APP_TINY_MCE_KEY=${{ secrets.REACT_APP_TINY_MCE_KEY }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.PROD_REACT_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.PROD_REACT_APP_FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.PROD_REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.PROD_REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.PROD_REACT_APP_FIREBASE_APP_ID }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.PROD_REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.PROD_REACT_APP_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.PROD_REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
    
      - name: Set Dev Environment Variables 🚀
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/setup-better-ci-cd'
        run: |
            echo "Setting Development branch secrets..."
            echo "Using repository secrets for $BRANCH branch..."
            echo "REACT_APP_SENTRY_DSN=${{ secrets.REACT_APP_SENTRY_DSN }}" >> $GITHUB_ENV
            echo "REACT_APP_TINY_MCE_KEY=${{ secrets.REACT_APP_TINY_MCE_KEY }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
  
      - name: Install dependencies  
        run: |
              npm  i --legacy-peer-deps
      
      - name: Build App 🏗
        run: |
            make build
        
      - name: Deploying to Prod 🚀 
        if: github.ref.base_ref == 'refs/heads/master'
        uses: data-intuitive/netlify-deploy-site@v1
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          dir: 'build'
          site: ${{ secrets.NETLIFY_PROD_SITE_ID }}
          prod: true
          message: 'Deploying ${{ github.ref }}'
    
      
      - name: Deploying to Canary 🚀
        if: github.ref == 'refs/heads/canary'
        uses: data-intuitive/netlify-deploy-site@v1
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          dir: 'build'
          site: ${{ secrets.NETLIFY_CANARY_SITE_ID }}
          prod: true
          message: 'Deploying ${{ github.ref }}'

      - name: Deploying  to Dev 🚀
        if: github.ref == 'refs/heads/development' 
        uses: data-intuitive/netlify-deploy-site@v1
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          dir: 'build'
          site: ${{ secrets.NETLIFY_DEV_SITE_ID }}
          prod: true
          message: 'Deploying ${{ github.ref }}'

      - name: Report status to Slack
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          BUILD_VERSION=$(jq -r '.BUILD_VERSION' < app/config/config.json)
          MESSAGE="Workflow in $BRANCH_NAME with build version : $BRANCH_NAME has completed with status: *${{ job.status }}*"
          PAYLOAD="{\"text\": \"$MESSAGE\"}"
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
